# Generated by Django 4.2 on 2023-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PR', 'In Progress'), ('DN', 'Done'), ('NO', 'Incomplete')], default='PR', max_length=2)),
            ],
        ),
    ]
